
package uibancosfalidos;

import entidadesbancosfalidos.InformacoesBanco;
import entidadesbancosfalidos.Banco;
import java.util.List;
import java.util.ResourceBundle;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.ScatterChart;
import javafx.scene.chart.XYChart;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.JTable;
import java.awt.Color;

public class TelaInicial extends javax.swing.JFrame {

    private InformacoesBanco anoBancos;
    ResourceBundle uis;
    /**
     * Creates new form TelaInicial
     * @param anoBancos
     */
    public TelaInicial(InformacoesBanco anoBancos) {
        initComponents();
        this.anoBancos = anoBancos;
        inicializarComboBoxDatasTodas();
        inicializarSliderAnos();
        getContentPane().setBackground(Color.black);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setBounds(300, 200, 400, 300);
       }
    
        
    /*Inicializar combo usando modelo*/
    private void inicializarComboBoxDatas(){
        List<String> nomeBancos = anoBancos.datasAno;
        DefaultComboBoxModel model = new DefaultComboBoxModel(nomeBancos.toArray(new String[nomeBancos.size()]));
        this.cmbDatas.setModel(model);
    }
    
    /*Inicializar combo usando metodo addItem do combobox para incluir a opcao TODAS as datas*/
    private void inicializarComboBoxDatasTodas(){
        List<String> anoDatas = anoBancos.datasAno;

        this.cmbDatas.addItem("TODAS");
        for(String nome: anoDatas){
                    this.cmbDatas.addItem(nome);
        }
    }
    
    
    
    private void inicializarSliderAnos(){
        sliderAno.setMinimum(0);
        sliderAno.setMaximum(2017);
        sliderAno.setMajorTickSpacing(2);
        sliderAno.setMinorTickSpacing(1);
        sliderAno.setPaintTicks(true);
        sliderAno.setPaintLabels(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabBuscarBanco = new javax.swing.JTabbedPane();
        jPanelBuscarUmBanco = new javax.swing.JPanel();
        btnBuscarUmBanco = new javax.swing.JButton();
        lblCERT = new javax.swing.JLabel();
        txtCERTBuscarUmBancp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUmBanco = new javax.swing.JTable();
        btnVerDatasBuscarCERT = new javax.swing.JButton();
        jPanelBuscarPorOutrosFiltros = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnBuscarVariosBancos = new javax.swing.JButton();
        cmbDatas = new javax.swing.JComboBox<>();
        lblDatas = new javax.swing.JLabel();
        sliderAno = new javax.swing.JSlider();
        lblAno = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVariosBancos = new javax.swing.JTable();
        lblTituloBuscador = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBuscarUmBanco.setVerifyInputWhenFocusTarget(false);

        btnBuscarUmBanco.setText("Buscar");
        btnBuscarUmBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUmBancoActionPerformed(evt);
            }
        });

        lblCERT.setText("CERT:");

        tblUmBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblUmBanco);

        btnVerDatasBuscarCERT.setText("Ver Ano");
        btnVerDatasBuscarCERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDatasBuscarCERTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarUmBancoLayout = new javax.swing.GroupLayout(jPanelBuscarUmBanco);
        jPanelBuscarUmBanco.setLayout(jPanelBuscarUmBancoLayout);
        jPanelBuscarUmBancoLayout.setHorizontalGroup(
            jPanelBuscarUmBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarUmBancoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelBuscarUmBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBuscarUmBancoLayout.createSequentialGroup()
                        .addComponent(btnBuscarUmBanco)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerDatasBuscarCERT))
                    .addGroup(jPanelBuscarUmBancoLayout.createSequentialGroup()
                        .addComponent(lblCERT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCERTBuscarUmBancp, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBuscarUmBancoLayout.setVerticalGroup(
            jPanelBuscarUmBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarUmBancoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelBuscarUmBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCERT)
                    .addComponent(txtCERTBuscarUmBancp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBuscarUmBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarUmBanco)
                    .addComponent(btnVerDatasBuscarCERT))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabBuscarBanco.addTab("Buscar por CERT", jPanelBuscarUmBanco);

        lblNome.setText("Nome do Banco :");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnBuscarVariosBancos.setText("Buscar");
        btnBuscarVariosBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVariosBancosActionPerformed(evt);
            }
        });

        lblDatas.setText("Período:");

        lblAno.setText("Ano que Faliu:");

        tblVariosBancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblVariosBancos);

        javax.swing.GroupLayout jPanelBuscarPorOutrosFiltrosLayout = new javax.swing.GroupLayout(jPanelBuscarPorOutrosFiltros);
        jPanelBuscarPorOutrosFiltros.setLayout(jPanelBuscarPorOutrosFiltrosLayout);
        jPanelBuscarPorOutrosFiltrosLayout.setHorizontalGroup(
            jPanelBuscarPorOutrosFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarPorOutrosFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarPorOutrosFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBuscarPorOutrosFiltrosLayout.createSequentialGroup()
                        .addGroup(jPanelBuscarPorOutrosFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome)
                            .addComponent(lblDatas)
                            .addComponent(lblAno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBuscarPorOutrosFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarVariosBancos)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDatas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sliderAno, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelBuscarPorOutrosFiltrosLayout.setVerticalGroup(
            jPanelBuscarPorOutrosFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarPorOutrosFiltrosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBuscarPorOutrosFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBuscarPorOutrosFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatas)
                    .addComponent(cmbDatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelBuscarPorOutrosFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarVariosBancos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabBuscarBanco.addTab("Buscar por Outros Filtros", jPanelBuscarPorOutrosFiltros);

        lblTituloBuscador.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblTituloBuscador.setText("Buscar Bancos Falidos dos Estados Unidos da América");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblTituloBuscador))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabBuscarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTituloBuscador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabBuscarBanco)
                .addContainerGap())
        );

        jTabBuscarBanco.getAccessibleContext().setAccessibleName("Buscar por RA");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarUmBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUmBancoActionPerformed
        // TODO add your handling code here:
        String ra = this.txtCERTBuscarUmBancp.getText().trim();
        Banco aluno = this.anoBancos.buscarUmBanco(ra);
        System.out.println(aluno);
       if (aluno!=null)
       this.tblUmBanco.setModel(new BancosFalidosTableModel(this.anoBancos, 
                aluno));
       else{
           //this.tblUmBanco.setModel(null);
       }
    }//GEN-LAST:event_btnBuscarUmBancoActionPerformed

    private void btnBuscarVariosBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVariosBancosActionPerformed
        // TODO add your handling code here:
        this.tblVariosBancos.setModel(new BancosFalidosTableModel(this.anoBancos, 
                this.anoBancos.buscarBancos(this.txtNome.getText().trim().toLowerCase()),
                this.cmbDatas.getSelectedItem().toString()   ,
                this.sliderAno.getValue())
        );
       
    }//GEN-LAST:event_btnBuscarVariosBancosActionPerformed

    private void btnVerDatasBuscarCERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDatasBuscarCERTActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if ((this.txtCERTBuscarUmBancp.getText().trim()).equals("")) return;
        Banco aluno = this.anoBancos.buscarUmBanco(this.txtCERTBuscarUmBancp.getText().trim());
        JDialog janPl = new JDialog();
        JFXPanel fxPanel = new JFXPanel();
        janPl.add(fxPanel);
        janPl.setSize(800,600);
        janPl.setVisible(true);
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                initFX(fxPanel, aluno);
            }
       });
    }//GEN-LAST:event_btnVerDatasBuscarCERTActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    
     private void initFX(JFXPanel panel, Banco aluno) {
        final CategoryAxis xAxis = new CategoryAxis();
        final NumberAxis yAxis = new NumberAxis();
         xAxis.setLabel("Período");
         yAxis.setLabel("Ano");

        final BarChart<String,Number> bc = 
            new BarChart<>(xAxis,yAxis);
       
        bc.setTitle("Informações do banco : " + aluno.getNomebanco());
               
        XYChart.Series series1 = new XYChart.Series();
        series1.setName("Ano que Faliu");
        
        for(String nomeDisciplina: this.anoBancos.datasAno){
            series1.getData().add(new XYChart.Data(nomeDisciplina, aluno.retornarNota(nomeDisciplina)));
        }
        
        bc.getData().addAll(series1);
        Scene  scene  =  new  Scene(bc, 800,600);
        panel.setScene(scene);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*-- @1 Instanciar objeto InformacoesBanco --*/
        InformacoesBanco notasAlunos = new InformacoesBanco();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial(notasAlunos).setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUmBanco;
    private javax.swing.JButton btnBuscarVariosBancos;
    private javax.swing.JButton btnVerDatasBuscarCERT;
    private javax.swing.JComboBox<String> cmbDatas;
    private javax.swing.JPanel jPanelBuscarPorOutrosFiltros;
    private javax.swing.JPanel jPanelBuscarUmBanco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabBuscarBanco;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCERT;
    private javax.swing.JLabel lblDatas;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTituloBuscador;
    private javax.swing.JSlider sliderAno;
    private javax.swing.JTable tblUmBanco;
    private javax.swing.JTable tblVariosBancos;
    private javax.swing.JTextField txtCERTBuscarUmBancp;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
